# Generated by Django 4.2.1 on 2024-02-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0002_g1level_g1_lexical_div_q_l1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgtext',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Класс'),
        ),
    ]
