# Generated by Django 4.2.1 on 2024-01-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj', '0003_alter_compoundword_options_alter_freqword_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='g1level',
            name='g1_lexical_div_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разннобразие 1.1'),
        ),
        migrations.AddField(
            model_name='g1level',
            name='g1_lexical_div_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разннобразие 1.2'),
        ),
        migrations.AddField(
            model_name='g1level',
            name='g1_lexical_div_q_l3',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разннобразие 1.3'),
        ),
        migrations.AddField(
            model_name='g2level',
            name='g2_lexical_div_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разннобразие 2.1'),
        ),
        migrations.AddField(
            model_name='g2level',
            name='g2_lexical_div_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разннобразие 2.2'),
        ),
        migrations.AddField(
            model_name='g3level',
            name='g3_lexical_div_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разннобразие 3.1'),
        ),
        migrations.AddField(
            model_name='g3level',
            name='g3_lexical_div_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разннобразие 3.1'),
        ),
        migrations.AddField(
            model_name='g4level',
            name='g4_lexical_div_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разннобразие 4.1'),
        ),
        migrations.AddField(
            model_name='g4level',
            name='g4_lexical_div_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разннобразие 4.2'),
        ),
    ]
