# Generated by Django 4.2.1 on 2024-01-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj', '0004_g1level_g1_lexical_div_q_l1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tjtext',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='g1level',
            name='g1_lexical_div_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 1.1'),
        ),
        migrations.AlterField(
            model_name='g1level',
            name='g1_lexical_div_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 1.2'),
        ),
        migrations.AlterField(
            model_name='g1level',
            name='g1_lexical_div_q_l3',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 1.3'),
        ),
        migrations.AlterField(
            model_name='g2level',
            name='g2_lexical_div_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разонобразие 2.1'),
        ),
        migrations.AlterField(
            model_name='g2level',
            name='g2_lexical_div_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 2.2'),
        ),
        migrations.AlterField(
            model_name='g3level',
            name='g3_lexical_div_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 3.1'),
        ),
        migrations.AlterField(
            model_name='g3level',
            name='g3_lexical_div_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 3.1'),
        ),
        migrations.AlterField(
            model_name='g4level',
            name='g4_lexical_div_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 4.1'),
        ),
        migrations.AlterField(
            model_name='g4level',
            name='g4_lexical_div_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 4.2'),
        ),
    ]
