# Generated by Django 4.2.1 on 2024-03-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uztext',
            name='grade',
        ),
    ]
