# Generated by Django 4.2.1 on 2024-02-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='g1level',
            name='g1_lexical_div_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 1.1'),
        ),
        migrations.AddField(
            model_name='g1level',
            name='g1_lexical_div_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 1.2'),
        ),
        migrations.AddField(
            model_name='g1level',
            name='g1_lexical_div_q_l3',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 1.3'),
        ),
        migrations.AddField(
            model_name='g2level',
            name='g2_lexical_div_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разонобразие 2.1'),
        ),
        migrations.AddField(
            model_name='g2level',
            name='g2_lexical_div_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 2.2'),
        ),
        migrations.AddField(
            model_name='g3level',
            name='g3_lexical_div_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 3.1'),
        ),
        migrations.AddField(
            model_name='g3level',
            name='g3_lexical_div_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 3.1'),
        ),
    ]
