# Generated by Django 4.2.1 on 2024-02-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0003_g4level_g4_lexical_div_q_l1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='g1level',
            name='g1_fre_oborneva_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Показатели удобочитаемости 1.1'),
        ),
        migrations.AddField(
            model_name='g1level',
            name='g1_fre_oborneva_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Показатели удобочитаемости 1.2'),
        ),
        migrations.AddField(
            model_name='g1level',
            name='g1_fre_oborneva_q_l3',
            field=models.FloatField(blank=True, null=True, verbose_name='Показатели удобочитаемости 1.3'),
        ),
        migrations.AddField(
            model_name='g2level',
            name='g2_fre_oborneva_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Показатели удобочитаемости 2.1'),
        ),
        migrations.AddField(
            model_name='g2level',
            name='g2_fre_oborneva_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Показатели удобочитаемости 2.2'),
        ),
        migrations.AddField(
            model_name='g3level',
            name='g3_fre_oborneva_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Показатели удобочитаемости 3.1'),
        ),
        migrations.AddField(
            model_name='g3level',
            name='g3_fre_oborneva_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Показатели удобочитаемости 3.2'),
        ),
        migrations.AddField(
            model_name='g4level',
            name='g4_fre_oborneva_q_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='Показатели удобочитаемости 3.1'),
        ),
        migrations.AddField(
            model_name='g4level',
            name='g4_fre_oborneva_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Показатели удобочитаемости 3.2'),
        ),
    ]
