# Generated by Django 4.2.1 on 2024-02-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0005_rutext_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g3level',
            name='g3_lexical_div_q_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='Лексическое разнообразие 3.2'),
        ),
    ]
